import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './Providers';
import Header from './components/shared/layout/Header';
import Footer from './components/shared/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Casul | Web',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es">
         <body className={inter.className}>
            <Providers>
               <Header />
               {children}
               <Footer />
            </Providers>
         </body>
      </html>
   );
}
